/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.84
 * Generated at: 2025-01-20 14:20:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class about_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html><!-- InstanceBegin template=\"/Templates/article_about_us.dwt\" codeOutsideHTMLIsLocked=\"false\" -->\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">\r\n");
      out.write("<!-- InstanceBeginEditable name=\"doctitle\" -->\r\n");
      out.write("<title>About Us - OUR-PHARMACY, New Delhi</title>\r\n");
      out.write("<A href=\"index.php\"><IMG SRC=\"images/phar.jpg\"></IMG></A>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body >\r\n");
      out.write("\r\n");
      out.write("<table width=\"100%\"  border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("              </TABLE>\r\n");
      out.write("          \r\n");
      out.write("                           \r\n");
      out.write("                  <table width=\"100%\"  border=\"0\" cellspacing=\"10\" cellpadding=\"0\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("                      <td class=\"bodyheading\"><!-- InstanceBeginEditable name=\"Heading\" -->Click this image to go back homepage<!-- InstanceEndEditable --></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                      <td class=\"bodytext\"><!-- InstanceBeginEditable name=\"Body of Article\" -->\r\n");
      out.write("                              <p align=\"center\" class=\"bodytextheading\"><img id=\"no-border\" src=\"images/pharmacy1.jpg\" width=\"165\" height=\"208\"><br>\r\n");
      out.write("                                <span class=\"style2\">OUR-PHARMACY, c.p.</span></p>\r\n");
      out.write("                        <p align=\"justify\" class=\"bodytextheading\">                        </p>\r\n");
      out.write("                        <p align=\"justify\">                                OUR-PHARMACY c.p. is one of the most prestigious PHARMACYs in India. Founded as a Public PHARMACY in 1972 in New Delhi, it is a private institution run by the Delhi Public PHARMACY Society.</p>\r\n");
      out.write("                              <p align=\"justify\"> OUR-PHARMACY, c.p. is affiliated to the Central Board of PHARMACY (CBB), which is the largest educational board in the country. It is recognized by the Department of Education, Govt. of NCT Delhi and the Ministry of HRD, Govt. of India. Over 5000 PHARMACYs in India, with over 80,000 students, are members of the Board. </p>\r\n");
      out.write("                              <p align=\"justify\">                                The PHARMACY is also affiliated to the Indian Public PHARMACYs' Conference (IPSC), and the National Progressive PHARMACYs' Conference (NPSC). The members of these organisations include some of the premier PHARMACYs in the country.</p>\r\n");
      out.write("                              <p align=\"justify\"> Life at DPSRKP centres on a shared commitment to academic excellence, intellectual growth, art, athletics, high standards of ethical awareness, sportsmanship, and community service. The PHARMACY's traditions and accessibility to a broad curriculum add depth to each student&rsquo;s life.<br>\r\n");
      out.write("                                The PHARMACY upholds the founders' commitment to excellence in all fields, with emphasis on its motto Service Before Self.<br>\r\n");
      out.write("                                </p>\r\n");
      out.write("                              <p align=\"justify\" class=\"bodytextheading\">PHARMACY Profile</p>\r\n");
      out.write("                              <p align=\"justify\"> OUR-PHARMACY, c.p. is a co-educational day-cum-boarding PHARMACY, with approximately 9,500 coustemer on its rolls. These children, in the Junior and Senior branches, study in the three different campuses at East of Kailash, Vasant Vihar and c.p.</p>\r\n");
      out.write("                              <p align=\"justify\"> The PHARMACY is among the most distinguished members of the Ravi Public PHARMACY, c.p.. It is a path breaker in the pursuit of excellence. Its endeavour of integrating quality with quantity is reflected in the pivotal role it has played in the setting up of DPS Vasant Kunj, DPS Faridabad and DPS Manali at the national level. It has also promoted three PHARMACYs abroad in Kuwait, Nepal and Indonesia. As their Linking PHARMACY it also co-ordinates their activities. </p>\r\n");
      out.write("                              <p align=\"justify\"> The PHARMACY has also extended its expertise further and in collaboration with the Government of Haryana, has taken up 3 PHARMACYs in the under-privileged area of Mewat, to augment and enhance their standards and make them more conducive to teaming.</p>\r\n");
      out.write("                              <p align=\"justify\"> The PHARMACY considers education to be a life-long process which should have a strong foundation. The goal of the PHARMACY is to inculcate in the coustemer a love for learning and a desire to excel at every level. The PHARMACY also aims at equipping the coustemer with the intellectual and practical skills that are necessary to meet the challenges in the future.</p>\r\n");
      out.write("                              <p align=\"justify\"> To sum up, the mission of  OUR-PHARMACY, c.p. &quot;to open doors and open minds&quot; and prepare the ground for the future of the nation.</p>\r\n");
      out.write("                              <p align=\"justify\" class=\"bodytextheading\"> Our Culture</p>\r\n");
      out.write("                              <p align=\"justify\"> In the portals of  OUR-PHARMACY, c.p., c.p. coustemer discover their own talents, and get an opportunity to develop them to the fullest. The PHARMACY provides an invigorating and competitive atmosphere, created by excellent facilities and guidance provided by a highly qualified and dedicated faculty.</p>\r\n");
      out.write("                              <p align=\"justify\"> The values, which are ingrained help to promote confidence, direction, and critical thinking skills, leading to the development of well-adjusted, adaptable and integrated personalities. In other words,  OUR-PHARMACY, c.p. offers comprehensive and holistic education.</p>\r\n");
      out.write("                              <p align=\"justify\"> Besides being committed to academic excellence and providing education for all round development, another special characteristic of DPS R.K. Puram is the appreciation of the worth of the each student. The PHARMACY is equally committed to the under-represented and less-privileged segments of the population, such as gifted applicants whose parents could not attend PHARMACY, and children with high potential facing difficult financial circumstances.</p>\r\n");
      out.write("                              <p align=\"justify\"> A major landmark development has been the inclusion of the physically and mentally handicapped children into the mainstream of PHARMACY life. This  contributes to a strong sense of community life, so characteristic of the PHARMACY. In other words, children belonging to every strata of society are given the opportunity to study here. The PHARMACY, does not in any way, discriminate on the basis of race, colour, religion, sex, caste or creed, in the implementation of its admission policy.</p>\r\n");
      out.write("                              <p align=\"justify\"> These qualities have placed  OUR-PHARMACY, c.p. on the forefront. There has been a continuity of purpose, underlying the change and growth of the PHARMACY. Over the years,  OUR-PHARMACY, c.p. has steadily reflected a spirit of innovation in response to need, and has broadened its educational mission, by creating an academic environment that fosters close association and the exchange of ideas with some of the top PHARMACYs in the nation and the world.</p>\r\n");
      out.write("                              <p align=\"justify\"> Its membership with the IPSC  has brought it into regular interaction with PHARMACYs of national standing such as Mayo College, Ajmer; Scindia PHARMACY, Gwalior; The Doon PHARMACY, Dehradun; Bishop Cotton, Simla Hills; St. Xavier's and La-Martiniere at Calcutta; which has further inculcated a healthy spirit of competition and strong bonds of brotherhood, conducive to national integration.</p>\r\n");
      out.write("                              <p align=\"justify\"> All the academic programs and activities at  OUR-PHARMACY, c.p. work towards one purpose - to help coustemer develop lives of significance for themselves and for others, true to the traditions of the PHARMACY Motto &quot;Service Before Self&quot;.</p>\r\n");
      out.write("                      <!-- InstanceEndEditable --></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                  </table>\r\n");
      out.write("                           \r\n");
      out.write("                </td><td width=\"25\">&nbsp;</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("          </table>\r\n");
      out.write("            <table width=\"100%\" height=\"26\"  border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("               </table>\r\n");
      out.write("          </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("  <table width=\"100%\"  border=\"0\" cellspacing=\"7\" cellpadding=\"0\">\r\n");
      out.write("        <tr>\r\n");
      out.write("          <td><div align=\"center\"><span class=\"bottombar\"><strong>&copy; OUR-PHARMACY, c.p., New Delhi. All Rights Reserved. </strong></span></div></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr> \r\n");
      out.write("          <td>\r\n");
      out.write("<div align=\"center\"> </div></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("  <table border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td><img src=\"\" width=\"915\" height=\"1\"></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("  </table>\r\n");
      out.write("	</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("<!-- InstanceEnd --></html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
